<template>
  <nav
    id="nav"
    class="
      flex
      justify-between
      bg-nav
      py-4
      px-[15px]
      lg:px-[var(--nav-section)]
      md:px-[var(--md-nav-section)]
    "
  >
    <img
      class="
        w-[127px]
        cursor-pointer
        self-center
        lg:w-[163.6px]
      "
      src="@/assets/images/logo.svg"
      alt="Pago de Banco de Chile"
    >
    <div
      class="
        hidden
        w-full
        justify-center
        self-center
        text-white
        gap-5
        font-semibold
        text-xs
        leading-6
        uppercase
        lg:flex
        lg:gap-12
        md:flex
        md:gap-12
      "
    >
      <p class="cursor-pointer self-center">Productos y Tarifas</p>
      <p class="cursor-pointer self-center">COMO CONTRATAR</p>
      <p class="cursor-pointer self-center">beneficios</p>
    </div>
    <div
      class="
        flex
        gap-4
        self-center
        lg:gap-0
      "
    >
      <button
        class="
          py-1.5
          px-4
          w-[120px]
          bg-btn-fill
          rounded-full
          text-xs
          uppercase
          leading-6
          font-bold
          cursor-pointer
          md:py-2
          lg:w-max

        "
      >
        <p>
          <span class="
            hidden
            lg:inline-block
          ">QUIERO</span> CONTRATAR
        </p>
      </button>
      <img
        class="
          cursor-pointer
          md:hidden
        "
        src="@/assets/icons/menu-bars.svg"
        alt="menu"
      >
    </div>
  </nav>
</template>
